pings/config/routes.rb
Rails.application.routes.draw do
  resources :epoches

  post '/clear_data', to: "devices#clear_data", as: :clear_data
  post '/:device_id(/:date)', to: "devices#create_device", as: :create_device

  get  '/all', to: "devices#get_all", as: :get_all
  get  '/devices', to: "devices#get_device_only", as: :get_device_only
  get  '/:device_id(/:date)', to: "devices#get_device", as: :get_device
  get  '/:device_id/:from/:to', to: "devices#get_device_from_to", as: :get_device_from_to

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

pings/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pings/app/models/device.rb
class Device < ApplicationRecord
  has_many :epoches, dependent: :delete_all
end

pings/app/models/epoch.rb
class Epoch < ApplicationRecord
  belongs_to :device

end

pings/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

pings/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # before_action :set_device, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /devices
  # GET /devices.json
  def clear_data
    Epoch.delete_all
    Device.delete_all
    head:ok
  end

  def create_device
    if  @device = Device.find_by_device_id(params[:device_id])
    else
      @device = Device.new(device_id_params)
      @device.save
    end
    @epoch = Epoch.new(epoch_params)
    @epoch.device_id = @device.id
    # date_format ="%Y-%m-%d"
    # DateTime.strptime(@epoch.date, date_format)
    @epoch.date = @epoch.date.to_i
    # render json: "matching format".to_json
    # rescue ArgumentError
    # false
    # render json: "doesnt match format".to_json
    @epoch.save
  end

  def get_device
    @device = Device.where(device_id: params[:device_id])
    @unix = params[:date]
    if @unix
      if @unix.include? "-"
        @unix = @unix.to_time.to_i
      else
      end
    else
    end
    @epoch = Epoch.find_by_date(@unix)
    @response = {}
    @device.each do | device |
      device.epoches.each do | epoch |
        epochunix = DateTime.strptime(epoch.date,'%s')
        if @response[device.device_id]
          @response[device.device_id].push(epochunix)
        else
          @response[device.device_id]= [epochunix]
        end
      end
    end
    render json: @response.to_json
  end

  def get_all
    @device = Device.all
    @epoch = Epoch.all
    @response = {}
    @device.each do | device |
      device.epoches.each do | epoch |
        if @response[device.device_id]
          @response[device.device_id].push(epoch.date)
        else
          @response[device.device_id]= [epoch.date]
        end
      end
    end
    render json: @response.to_json
  end

  def get_device_only
    @device = Device.all
    @response = []
    @device.each do | device |
      @response.push(device.device_id)
    end
    render json: @response.to_json
  end

  def index
    @devices = Device.all
  end

  def get_device_from_to
    @device = Device.where(device_id: params[:device_id])
    @from = params[:from]
    @to = params[:to]
    if @to.include? "-"
      @to_unix = @to.to_time.to_i
      else
        @to_unix = @to
    end
    if @from.include? "-"
      @from_unix = @from.to_time.to_i
      else
        @from_unix = @from
    end
    @to_unix = @to_unix.to_i
    @from_unix = @from_unix.to_i
    @response = []
    @device[0].epoches.each do | epoch |
      if epoch.date >= @from_unix && epoch.date < @to_unix
          @response.push(epoch.date)
      end
    end
      render json: @response.to_json
  end


  # # GET /devices/1
  # # GET /devices/1.json
  # def show
  # end
  #
  # # GET /devices/new
  # def new
  #   @device = Device.new
  # end
  #
  # # GET /devices/1/edit
  # def edit
  # end
  #
  # # POST /devices
  # # POST /devices.json
  # def create
  #   @device = Device.new(device_params)
  #
  #   respond_to do |format|
  #     if @device.save
  #       format.html { redirect_to @device, notice: 'Device was successfully created.' }
  #       format.json { render :show, status: :created, location: @device }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @device.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /devices/1
  # # PATCH/PUT /devices/1.json
  # def update
  #   respond_to do |format|
  #     if @device.update(device_params)
  #       format.html { redirect_to @device, notice: 'Device was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @device }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @device.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /devices/1
  # # DELETE /devices/1.json
  # def destroy
  #   @device.destroy
  #   respond_to do |format|
  #     format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # # Use callbacks to share common setup or constraints between actions.
    # def set_device
    #   @device = Device.find(params[:id])
    # end
    #
    # # Never trust parameters from the scary internet, only allow the white list through.
    def device_id_params
      params.permit(:device_id)
    end

    def epoch_params
      params.permit(:date)
    end
end

pings/app/controllers/epoches_controller.rb
class EpochesController < ApplicationController
  before_action :set_epoch, only: [:show, :edit, :update, :destroy]

  # GET /epoches
  # GET /epoches.json
  def index
    @epoches = Epoch.all
  end

  # GET /epoches/1
  # GET /epoches/1.json
  def show
  end

  # GET /epoches/new
  def new
    @epoch = Epoch.new
  end

  # GET /epoches/1/edit
  def edit
  end

  # POST /epoches
  # POST /epoches.json
  def create
    @epoch = Epoch.new(epoch_params)

    respond_to do |format|
      if @epoch.save
        format.html { redirect_to @epoch, notice: 'Epoch was successfully created.' }
        format.json { render :show, status: :created, location: @epoch }
      else
        format.html { render :new }
        format.json { render json: @epoch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epoches/1
  # PATCH/PUT /epoches/1.json
  def update
    respond_to do |format|
      if @epoch.update(epoch_params)
        format.html { redirect_to @epoch, notice: 'Epoch was successfully updated.' }
        format.json { render :show, status: :ok, location: @epoch }
      else
        format.html { render :edit }
        format.json { render json: @epoch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epoches/1
  # DELETE /epoches/1.json
  def destroy
    @epoch.destroy
    respond_to do |format|
      format.html { redirect_to epoches_url, notice: 'Epoch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epoch
      @epoch = Epoch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epoch_params
      params.require(:epoch).permit(:time, :device_id)
    end
end

pings/app/helpers/application_helper.rb
module ApplicationHelper
end

pings/app/helpers/devices_helper.rb
module DevicesHelper
end

pings/app/helpers/epoches_helper.rb
module EpochesHelper
end

pings/app/views/devices/_form.html.erb
<%= form_with(model: device, local: true) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :device_id %>
    <%= form.text_field :device_id, id: :device_device_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

pings/app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

pings/app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>

<table>
  <thead>
    <tr>
      <th>Device</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.device_id %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

pings/app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

pings/app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device:</strong>
  <%= @device.device_id %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

pings/app/views/epoches/_form.html.erb
<%= form_with(model: epoch, local: true) do |form| %>
  <% if epoch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(epoch.errors.count, "error") %> prohibited this epoch from being saved:</h2>

      <ul>
      <% epoch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time, id: :epoch_time %>
  </div>

  <div class="field">
    <%= form.label :device_id %>
    <%= form.text_field :device_id, id: :epoch_device_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

pings/app/views/epoches/edit.html.erb
<h1>Editing Epoch</h1>

<%= render 'form', epoch: @epoch %>

<%= link_to 'Show', @epoch %> |
<%= link_to 'Back', epoches_path %>

pings/app/views/epoches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Epoches</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Device</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @epoches.each do |epoch| %>
      <tr>
        <td><%= epoch.time %></td>
        <td><%= epoch.device %></td>
        <td><%= link_to 'Show', epoch %></td>
        <td><%= link_to 'Edit', edit_epoch_path(epoch) %></td>
        <td><%= link_to 'Destroy', epoch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Epoch', new_epoch_path %>

pings/app/views/epoches/new.html.erb
<h1>New Epoch</h1>

<%= render 'form', epoch: @epoch %>

<%= link_to 'Back', epoches_path %>

pings/app/views/epoches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @epoch.time %>
</p>

<p>
  <strong>Device:</strong>
  <%= @epoch.device %>
</p>

<%= link_to 'Edit', edit_epoch_path(@epoch) %> |
<%= link_to 'Back', epoches_path %>

pings/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pings</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>